### ISSUE TITLE
{To,From}Avro (Either a b) are Left-biased when (a ~ b)

### ISSUE THREAD

**Issue by Icelandjack** [GaloisInc/avro#4]
Avro does not distinguish between `Left` and `Right` branch

```haskell
>>> toAvro (Left "str" :: Either Text Text)
Union (String :| [String]) String (String "str")

>>> toAvro (Right "str" :: Either Text Text)
Union (String :| [String]) String (String "str")
```

so converting back from Avro gives a `Left` regardless of the original constructor

```haskell
>>> fromAvro (toAvro (Left "str" :: Either Text Text)) :: Result (Either Text Text)
Success (Left "str")

>>> fromAvro (toAvro (Right "str" :: Either Text Text)) :: Result (Either Text Text)
Success (Left "str")
```

**Comment by AlexeyRaga** [comment]
I am not sure if it is incorrect though.
Avro specification defines union at a type level:
> For example, ["null", "string"] declares a schema which may be either a null or string.

So from the Avro point of view you are saying "this type must be either String or String". Well, it is String, that's what Avro tells you in return. 

More on that:
> Unions may not contain more than one schema with the same type, except for the named types record, fixed and enum. For example, unions containing two array types or two map types are not permitted, but two types with different names are permitted. (Names permit efficient resolution when reading and writing unions.)

So having a union of `["string", "string"]` doesn't seem to be complying to the specification.

**Comment by Icelandjack** [comment]
That's a fine view but I would probably introduce a new type with the untagged-union semantics, I expect a tagged union when using `Either`.

**Comment by AlexeyRaga** [comment]
Interesting. By "a new type with the untagged-union semantics" you mean your own record type in terms of Avro? I think it can be done on the client side, at least in the mean time.

I think this is not limited `Either a a`, many times `mkUnion` is used directly in the code and it currently has no checks for type uniqueness. Ideally it should be done at the compile time, but I don't know how :)

It is also the case of `Either a a` is not unique because nothing stops me to use `Either a b` where `b` is just a `newtype` for `a` deriving `ToAvro`, etc...

**Comment by AlexeyRaga** [comment]
Should we close this issue?

**Comment by Icelandjack** [comment]
Sure
