### ISSUE TITLE
Avro and lazy decoding

### ISSUE THREAD

**Issue by AlexeyRaga** [GaloisInc/avro#41]
I am not actually starting any work on this now and opening this issue as a discussion point.

The problem is that the `decodeContainer` has the following signature:
```
decodeContainer :: BL.ByteString -> Either String (Schema, [[T.Value Type]])
```
which means that in order to return the result it must know whether there was an error or a success for the entire structure. Which means that the value in `Right` is fully traversed before it is returned and that `[[T.Value Type]]` is never lazy.

It comes all the way from 
```
getContainerWith :: (Schema -> Get a) -> Get (Schema, [[a]])
``` 
which decodes and decompresses the bytestring and then calls `runGetOrFail` once for the whole structure in this block (wrapping the result back to `Get` to hide its crime):
```
case runGetOrFail (replicateM nrObj getValue) bytes of
    Right (_,_,x) -> return x
    Left (_,_,s)  -> fail s
```

I am not very familiar with `Get`, but If we somehow could call `runGetOrFail` on each chunk separately, then we could be "lazier".

Or we can go all the way and have an error case as another constructor of `Value` so that we could lazily decode the structure without forcing the full traversal on it (which `Either Error a` does).

Does anyone else think it is worth improving and can offer their thoughts on the subject?

@newhoggy , @TikhonJelvis ?

**Comment by TikhonJelvis** [comment]
I had a chat with Alex about Avro and streaming this morning. Incrementally parsing each *block* in a container ought to be straightforward. If one block has a parse error, we can recover at the start of the next block by jumping to the next "synchronization marker":

> each block's binary data can be efficiently extracted or skipped without deserializing the contents. The combination of block size, object counts, and sync markers enable detection of corrupt blocks and help ensure data integrity.

This means we can change the signature of `decodeContainer` to something like:

```
decodeContainer :: BL.ByteString -> Either String (Schema, [Either String [T.Value Type]])
```

Having nested `Either`s like this is definitely awkward but it gives us the behavior we need:

  * the outer `Either` triggers if the file header is invalid (which includes the schema)
  * each block has its own `Either` so that it is parsed separately and an error in one block does not prevent us from parsing other blocks

In principle, we should also be able to skip blocks altogether without parsing them by jumping to the sync markers. Actually enabling this behavior might require a bit of extra care in the implementation of `decodeContainer`.

I prefer the slightly awkward nested `Either`s over having an `Error` constructor in `Value`. Adding an `Error` case to `Value` would require special logic in every single function that processes records and doesn't really reflect how the format works. Also, at least in the approach I'm outlining here, errors happened at a granularity of *blocks*, not individual records.

I will need to take a deeper look at the code to see what it would take to implement this, but it seems relatively doable and is a pretty small change to the API.

**Comment by alexbiehl** [comment]
I made some experiments today and somewhat converged on this code: 

```haskell
data Blocks a
  = Block a (Blocks a)
  | Error String (Maybe (Blocks a))
  | Empty

data RawBlock =
  RawBlock !Int64 !Int64 !BL.ByteString

getContainerWith' :: BL.ByteString -> Either String (Schema, Blocks RawBlock)
getContainerWith' input =
  case runGetOrFail getAvro input of
    Right (rest, _, header) ->
      let
        blocks =
          getBlocks1 rest
      in
        Right (containedSchema header, blocks)
    Left (_, _, err) ->
      Left err

  where
    getBlocks1 :: BL.ByteString -> Blocks RawBlock
    getBlocks1 bytes
      | BL.null bytes =
          Empty
      | otherwise =
        let
          getBlockHeader = do
            nrObjects <- sFromIntegral =<< getLong
            nrBytes   <- getLong
            pure (nrObjects, nrBytes)
        in
          case runGetOrFail getBlockHeader bytes of
            Right (bytes', _, (!nrObjects, !nrBytes)) ->
              let
                ~(block, rest) =
                  BL.splitAt nrBytes bytes'
              in
                Block
                  (RawBlock nrObjects nrBytes block)
                  (getBlocks1 rest)
            Left (_, _, err) ->
              Error err Nothing
```

The above design 
- allows fast skipping over blocks
- decouples parsing of blocks from parsing of actual Avro values and thus nicely separates the problem

Just throwing this into the discussion, maybe this helps to find out what we want and what we don't want.

**Comment by alexbiehl** [comment]
One addendum to lazy fields vs. lazy blocks. Lazy blocks are inherently supported by Avro. Blocks are prefixed by their length. I don't need to look at the values to determine boundaries. 

Whereas we would "overlay" laziness in the lazy fields proposal. This has the implication that to skip fields, we still need to (deeply) traverse/partially deserialize every field in order to get the widths of each field before the one we are interested in.

**Comment by AlexeyRaga** [comment]
I have also found this code:
```
-- The writer's symbol must be present in the reader's enum
resolveEnum :: Type -> Type -> T.Value Type -> Either String (T.Value Type)
resolveEnum e d val@(T.Enum _ _ _txt) = Right val
  -- --  | txt `elem` symbols d = Right val
  -- --  | otherwise = Left "Decoded enum does not appear in reader's symbol list."
```

Which is not very reassuring, but it doesn't impact us and our cases (yet).
Perhaps at some point, we need to fix it too.
